# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [ ]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [ ]:
X = data[feature_cols]
Y = data["Sales"]

In [ ]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=2, step=1)
selector = selector.fit(X,Y)

In [ ]:
selector.support_

array([ True,  True, False])

In [ ]:
selector.ranking_

array([1, 1, 2])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
X_pred = X[["TV", "Radio"]]

In [ ]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression()

In [ ]:
lm.intercept_

2.921099912405138

In [ ]:
lm.coef_

array([0.04575482, 0.18799423])

In [ ]:
lm.score(X_pred, Y)

0.8971942610828956